"""empty message

Revision ID: a38764922bfd
Revises: c3033133e8c1
Create Date: 2021-12-16 23:23:13.581329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a38764922bfd'
down_revision = 'c3033133e8c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_name_key', 'user', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('user_name_key', 'user', ['name'])
    # ### end Alembic commands ###
